/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n  mutation Login($loginUserInput: LoginUserInput!) {\n    login(loginUserInput: $loginUserInput) {\n      access_token\n      user {\n        createdAt\n        email\n        id\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n": types.LoginDocument,
    "\n  mutation Signup($signupUserInput: CreateUserInput!) {\n    signup(signupUserInput: $signupUserInput) {\n      success\n    }\n  }\n": types.SignupDocument,
    "\n  mutation CreateItemCategory(\n    $createItemCategoryInput: CreateItemCategoryInput!\n  ) {\n    createItemCategory(createItemCategoryInput: $createItemCategoryInput) {\n      createdAt\n      id\n      name\n      updatedAt\n      Item {\n        id\n      }\n    }\n  }\n": types.CreateItemCategoryDocument,
    "\n  mutation DeleteItemCategory(\n    $deleteItemCategoryInput: DeleteItemCategoryInput!\n  ) {\n    deleteItemCategory(deleteItemCategoryInput: $deleteItemCategoryInput) {\n      createdAt\n      id\n      name\n    }\n  }\n": types.DeleteItemCategoryDocument,
    "\n  query CategoryItem($itemCategoryId: String!) {\n    itemCategory(id: $itemCategoryId) {\n      Item {\n        id\n      }\n      createdAt\n      id\n      name\n      updatedAt\n    }\n  }\n": types.CategoryItemDocument,
    "\n  query ItemCategories(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    itemCategories(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      itemCategories {\n        createdAt\n        id\n        name\n        parentCategory {\n          id\n        }\n        updatedAt\n        Item {\n          id\n        }\n      }\n    }\n  }\n": types.ItemCategoriesDocument,
    "\n  mutation UpdateItemCategory(\n    $updateItemCategoryInput: UpdateItemCategoryInput!\n  ) {\n    updateItemCategory(updateItemCategoryInput: $updateItemCategoryInput) {\n      Item {\n        id\n      }\n      createdAt\n      id\n      name\n      updatedAt\n    }\n  }\n": types.UpdateItemCategoryDocument,
    "\n  mutation ForgotPassword($forgotPasswordInput: ForgotPasswordInput!) {\n    forgotPassword(forgotPasswordInput: $forgotPasswordInput) {\n      token\n    }\n  }\n": types.ForgotPasswordDocument,
    "\n  mutation ValidateForgotPassword(\n    $forgotPasswordInput: ForgotPasswordConfirmationInput!\n  ) {\n    validateForgotPassword(forgotPasswordInput: $forgotPasswordInput) {\n      message\n    }\n  }\n": types.ValidateForgotPasswordDocument,
    "\n  query getPermissions {\n    getpermissions \n  }\n": types.GetPermissionsDocument,
    "\n  mutation CreateItem($createItemInput: CreateItemInput!) {\n    createItem(createItemInput: $createItemInput) {\n      Category {\n        createdAt\n        id\n        name\n        updatedAt\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n": types.CreateItemDocument,
    "\n  mutation ItemDelete($deleteItemInput: DeleteItemInput!) {\n    deleteItem(deleteItemInput: $deleteItemInput) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n": types.ItemDeleteDocument,
    "\n  query Item($itemId: String!) {\n    item(id: $itemId) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n": types.ItemDocument,
    "\n  query Items(\n    $filterArgs: FilterItemInputs\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    items(\n      filterArgs: $filterArgs\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      items {\n        baseUnit\n        createdAt\n        hsnCode\n        id\n        instructions\n        mrpBaseUnit\n        updatedAt\n        wholesalePrice\n        name\n        Category {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n": types.ItemsDocument,
    "\n  mutation UpdateItem($updateItemInput: UpdateItemInput!) {\n    updateItem(updateItemInput: $updateItemInput) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n": types.UpdateItemDocument,
    "\n  mutation CreateOrganization(\n    $createOrganizationInput: CreateOrganizationInput!\n  ) {\n    createOrganization(createOrganizationInput: $createOrganizationInput) {\n      active\n      address\n      city\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n      contact\n    }\n  }\n": types.CreateOrganizationDocument,
    "\n  mutation DeleteOrganization(\n    $deleteOrganizationInput: DeleteOrganizationInput!\n  ) {\n    deleteOrganization(deleteOrganizationInput: $deleteOrganizationInput) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n": types.DeleteOrganizationDocument,
    "\n  query Query($organizationId: String!) {\n    organization(id: $organizationId) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n": types.QueryDocument,
    "\n  query Organizations(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    organizations(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      organizations {\n        active\n        address\n        city\n        country\n        createdAt\n        description\n        id\n        name\n        updatedAt\n      }\n      total\n    }\n  }\n": types.OrganizationsDocument,
    "\n  mutation UpdateOrganization(\n    $updateOrganizationInput: UpdateOrganizationInput!\n  ) {\n    updateOrganization(updateOrganizationInput: $updateOrganizationInput) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n": types.UpdateOrganizationDocument,
    "\n  mutation CreatePharmacy($createPharmacyInput: CreatePharmacyInput!) {\n    createPharmacy(createPharmacyInput: $createPharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n": types.CreatePharmacyDocument,
    "\n  mutation DeletePharmacy($deletePharmacyInput: DeletePharmacyInput!) {\n    deletePharmacy(deletePharmacyInput: $deletePharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n": types.DeletePharmacyDocument,
    "\n  query Pharmacy($pharmacyId: String!) {\n    pharmacy(id: $pharmacyId) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      organization {\n        active\n        address\n        city\n        contact\n        country\n        createdAt\n        description\n        id\n        name\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n": types.PharmacyDocument,
    "\n  query Pharmacies(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    pharmacies(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      pharmacies {\n        contactInfo\n        createdAt\n        id\n        location\n        name\n        organization {\n          id\n          name\n        }\n        updatedAt\n      }\n      total\n    }\n  }\n": types.PharmaciesDocument,
    "\n  mutation UpdatePharmacy($updatePharmacyInput: UpdatePharmacyInput!) {\n    updatePharmacy(updatePharmacyInput: $updatePharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n": types.UpdatePharmacyDocument,
    "\n  mutation CreatePharmacyStock(\n    $createPharmacyStockInput: CreatePharmacyStockInput!\n  ) {\n    createPharmacyStock(createPharmacyStockInput: $createPharmacyStockInput) {\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      pharmacy {\n        id\n        name\n      }\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n": types.CreatePharmacyStockDocument,
    "\n  query PharmacyStock($pharmacyStockId: String!) {\n    PharmacyStock(id: $pharmacyStockId) {\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      pharmacy {\n        id\n        name\n      }\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n": types.PharmacyStockDocument,
    "\n  query PharmacyStocksByPharmacy(\n    $pharmacyId: String!\n    $paginationArgs: PaginationArgs\n  ) {\n    pharmacyStocksByPharmacy(\n      pharmacyId: $pharmacyId\n      paginationArgs: $paginationArgs\n    ) {\n      pharmacyStocks {\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        pharmacy {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n": types.PharmacyStocksByPharmacyDocument,
    "\n  query PharmacyStocks(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    PharmacyStocks(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      pharmacyStocks {\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        pharmacy {\n          id\n          name\n        }\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n": types.PharmacyStocksDocument,
    "\n  query Account {\n    account {\n      role\n      user {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n": types.AccountDocument,
    "\n  mutation UpdateProfile($updateProfileInput: UpdateProfileInput!) {\n    updateprofile(updateProfileInput: $updateProfileInput)\n  }\n": types.UpdateProfileDocument,
    "\n  mutation ResetPassword($resetPasswordInput: ResetPasswordInput!) {\n    resetPassword(resetPasswordInput: $resetPasswordInput)\n  }\n": types.ResetPasswordDocument,
    "\n  mutation Mutation($tokenConfirmationInput: TokenConfirmationInput!) {\n    tokenConfirmation(tokenConfirmationInput: $tokenConfirmationInput) {\n      access_token\n      user {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n": types.MutationDocument,
    "\n  mutation Create($createUserInput: CreateUserInput!) {\n    create(createUserInput: $createUserInput) {\n      createdAt\n      email\n      emailConfirmationToken\n      id\n      isEmailConfirmed\n      name\n      organization {\n        id\n        name\n      }\n      updatedAt\n      username\n      role {\n        id\n        name\n        userType\n      }\n    }\n  }\n": types.CreateDocument,
    "\n  query UserById($userByIdId: String!) {\n    userById(id: $userByIdId) {\n      createdAt\n      email\n      emailConfirmationToken\n      id\n      isEmailConfirmed\n      name\n      organization {\n        id\n        name\n      }\n      updatedAt\n      username\n      role {\n        id\n        name\n        userType\n      }\n    }\n  }\n": types.UserByIdDocument,
    "\n  query Users(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    users(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      users {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        organization {\n          id\n          name\n        }\n        updatedAt\n        username\n        role {\n          id\n          name\n          userType\n        }\n      }\n    }\n  }\n": types.UsersDocument,
    "\n  mutation CreateWarehouse($createWarehouseInput: CreateWarehouseInput!) {\n    createWarehouse(createWarehouseInput: $createWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        id\n        name\n      }\n    }\n  }\n": types.CreateWarehouseDocument,
    "\n  mutation DeleteWarehouse($deleteWarehouseInput: DeleteWarehouseInput!) {\n    deleteWarehouse(deleteWarehouseInput: $deleteWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n    }\n  }\n": types.DeleteWarehouseDocument,
    "\n  query WarehouseDetails($warehouseId: String!) {\n    warehouse(id: $warehouseId) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        name\n        id\n      }\n    }\n  }\n": types.WarehouseDetailsDocument,
    "\n  mutation GenerateSKU($generateSkuNameInput: CreateSkuNameInput!) {\n    generateSKU(generateSkuNameInput: $generateSkuNameInput) {\n      sku\n    }\n  }\n": types.GenerateSkuDocument,
    "\n  query WarehouseList(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    warehouses(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      warehouses {\n        area\n        createdAt\n        id\n        location\n        updatedAt\n        name\n        organization {\n          name\n          id\n        }\n      }\n    }\n  }\n": types.WarehouseListDocument,
    "\n  mutation WarehouseStockCreate(\n    $createWarehouseStockInput: CreateWarehouseStockInput!\n  ) {\n    createWarehouseStock(\n      createWarehouseStockInput: $createWarehouseStockInput\n    ) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n": types.WarehouseStockCreateDocument,
    "\n  mutation DeleteWarehouseStock(\n    $deleteWarehouseStockInput: DeleteWarehouseStockInput!\n  ) {\n    deleteWarehouseStock(\n      deleteWarehouseStockInput: $deleteWarehouseStockInput\n    ) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n": types.DeleteWarehouseStockDocument,
    "\n  query WarehouseStockDetails($warehouseStockId: String!) {\n    warehouseStock(id: $warehouseStockId) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n        organization {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.WarehouseStockDetailsDocument,
    "\n  query WarehouseStocks(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    warehouseStocks(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      warehouseStocks {\n        SKU {\n          id\n          sku\n        }\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.WarehouseStocksDocument,
    "\n  query WarehouseStocksByWarehouse(\n    $warehouseId: String!\n    $paginationArgs: PaginationArgs\n  ) {\n    warehouseStocksByWarehouse(\n      warehouseId: $warehouseId\n      paginationArgs: $paginationArgs\n    ) {\n      total\n      warehouseStocks {\n        SKU {\n          id\n          sku\n        }\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.WarehouseStocksByWarehouseDocument,
    "\n  mutation UpdateWarehouseMutation(\n    $updateWarehouseInput: UpdateWarehouseInput!\n  ) {\n    updateWarehouse(updateWarehouseInput: $updateWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        id\n        name\n      }\n    }\n  }\n": types.UpdateWarehouseMutationDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Login($loginUserInput: LoginUserInput!) {\n    login(loginUserInput: $loginUserInput) {\n      access_token\n      user {\n        createdAt\n        email\n        id\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Login($loginUserInput: LoginUserInput!) {\n    login(loginUserInput: $loginUserInput) {\n      access_token\n      user {\n        createdAt\n        email\n        id\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Signup($signupUserInput: CreateUserInput!) {\n    signup(signupUserInput: $signupUserInput) {\n      success\n    }\n  }\n"): (typeof documents)["\n  mutation Signup($signupUserInput: CreateUserInput!) {\n    signup(signupUserInput: $signupUserInput) {\n      success\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateItemCategory(\n    $createItemCategoryInput: CreateItemCategoryInput!\n  ) {\n    createItemCategory(createItemCategoryInput: $createItemCategoryInput) {\n      createdAt\n      id\n      name\n      updatedAt\n      Item {\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateItemCategory(\n    $createItemCategoryInput: CreateItemCategoryInput!\n  ) {\n    createItemCategory(createItemCategoryInput: $createItemCategoryInput) {\n      createdAt\n      id\n      name\n      updatedAt\n      Item {\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteItemCategory(\n    $deleteItemCategoryInput: DeleteItemCategoryInput!\n  ) {\n    deleteItemCategory(deleteItemCategoryInput: $deleteItemCategoryInput) {\n      createdAt\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteItemCategory(\n    $deleteItemCategoryInput: DeleteItemCategoryInput!\n  ) {\n    deleteItemCategory(deleteItemCategoryInput: $deleteItemCategoryInput) {\n      createdAt\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CategoryItem($itemCategoryId: String!) {\n    itemCategory(id: $itemCategoryId) {\n      Item {\n        id\n      }\n      createdAt\n      id\n      name\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query CategoryItem($itemCategoryId: String!) {\n    itemCategory(id: $itemCategoryId) {\n      Item {\n        id\n      }\n      createdAt\n      id\n      name\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ItemCategories(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    itemCategories(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      itemCategories {\n        createdAt\n        id\n        name\n        parentCategory {\n          id\n        }\n        updatedAt\n        Item {\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ItemCategories(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    itemCategories(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      itemCategories {\n        createdAt\n        id\n        name\n        parentCategory {\n          id\n        }\n        updatedAt\n        Item {\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateItemCategory(\n    $updateItemCategoryInput: UpdateItemCategoryInput!\n  ) {\n    updateItemCategory(updateItemCategoryInput: $updateItemCategoryInput) {\n      Item {\n        id\n      }\n      createdAt\n      id\n      name\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateItemCategory(\n    $updateItemCategoryInput: UpdateItemCategoryInput!\n  ) {\n    updateItemCategory(updateItemCategoryInput: $updateItemCategoryInput) {\n      Item {\n        id\n      }\n      createdAt\n      id\n      name\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ForgotPassword($forgotPasswordInput: ForgotPasswordInput!) {\n    forgotPassword(forgotPasswordInput: $forgotPasswordInput) {\n      token\n    }\n  }\n"): (typeof documents)["\n  mutation ForgotPassword($forgotPasswordInput: ForgotPasswordInput!) {\n    forgotPassword(forgotPasswordInput: $forgotPasswordInput) {\n      token\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ValidateForgotPassword(\n    $forgotPasswordInput: ForgotPasswordConfirmationInput!\n  ) {\n    validateForgotPassword(forgotPasswordInput: $forgotPasswordInput) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation ValidateForgotPassword(\n    $forgotPasswordInput: ForgotPasswordConfirmationInput!\n  ) {\n    validateForgotPassword(forgotPasswordInput: $forgotPasswordInput) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query getPermissions {\n    getpermissions \n  }\n"): (typeof documents)["\n  query getPermissions {\n    getpermissions \n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateItem($createItemInput: CreateItemInput!) {\n    createItem(createItemInput: $createItemInput) {\n      Category {\n        createdAt\n        id\n        name\n        updatedAt\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation CreateItem($createItemInput: CreateItemInput!) {\n    createItem(createItemInput: $createItemInput) {\n      Category {\n        createdAt\n        id\n        name\n        updatedAt\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ItemDelete($deleteItemInput: DeleteItemInput!) {\n    deleteItem(deleteItemInput: $deleteItemInput) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation ItemDelete($deleteItemInput: DeleteItemInput!) {\n    deleteItem(deleteItemInput: $deleteItemInput) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Item($itemId: String!) {\n    item(id: $itemId) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n"): (typeof documents)["\n  query Item($itemId: String!) {\n    item(id: $itemId) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Items(\n    $filterArgs: FilterItemInputs\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    items(\n      filterArgs: $filterArgs\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      items {\n        baseUnit\n        createdAt\n        hsnCode\n        id\n        instructions\n        mrpBaseUnit\n        updatedAt\n        wholesalePrice\n        name\n        Category {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n"): (typeof documents)["\n  query Items(\n    $filterArgs: FilterItemInputs\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    items(\n      filterArgs: $filterArgs\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      items {\n        baseUnit\n        createdAt\n        hsnCode\n        id\n        instructions\n        mrpBaseUnit\n        updatedAt\n        wholesalePrice\n        name\n        Category {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateItem($updateItemInput: UpdateItemInput!) {\n    updateItem(updateItemInput: $updateItemInput) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateItem($updateItemInput: UpdateItemInput!) {\n    updateItem(updateItemInput: $updateItemInput) {\n      Category {\n        id\n        name\n      }\n      baseUnit\n      createdAt\n      hsnCode\n      id\n      instructions\n      mrpBaseUnit\n      updatedAt\n      wholesalePrice\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateOrganization(\n    $createOrganizationInput: CreateOrganizationInput!\n  ) {\n    createOrganization(createOrganizationInput: $createOrganizationInput) {\n      active\n      address\n      city\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n      contact\n    }\n  }\n"): (typeof documents)["\n  mutation CreateOrganization(\n    $createOrganizationInput: CreateOrganizationInput!\n  ) {\n    createOrganization(createOrganizationInput: $createOrganizationInput) {\n      active\n      address\n      city\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n      contact\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteOrganization(\n    $deleteOrganizationInput: DeleteOrganizationInput!\n  ) {\n    deleteOrganization(deleteOrganizationInput: $deleteOrganizationInput) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteOrganization(\n    $deleteOrganizationInput: DeleteOrganizationInput!\n  ) {\n    deleteOrganization(deleteOrganizationInput: $deleteOrganizationInput) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Query($organizationId: String!) {\n    organization(id: $organizationId) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query Query($organizationId: String!) {\n    organization(id: $organizationId) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Organizations(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    organizations(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      organizations {\n        active\n        address\n        city\n        country\n        createdAt\n        description\n        id\n        name\n        updatedAt\n      }\n      total\n    }\n  }\n"): (typeof documents)["\n  query Organizations(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    organizations(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      organizations {\n        active\n        address\n        city\n        country\n        createdAt\n        description\n        id\n        name\n        updatedAt\n      }\n      total\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateOrganization(\n    $updateOrganizationInput: UpdateOrganizationInput!\n  ) {\n    updateOrganization(updateOrganizationInput: $updateOrganizationInput) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateOrganization(\n    $updateOrganizationInput: UpdateOrganizationInput!\n  ) {\n    updateOrganization(updateOrganizationInput: $updateOrganizationInput) {\n      active\n      address\n      city\n      contact\n      country\n      createdAt\n      description\n      id\n      name\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreatePharmacy($createPharmacyInput: CreatePharmacyInput!) {\n    createPharmacy(createPharmacyInput: $createPharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePharmacy($createPharmacyInput: CreatePharmacyInput!) {\n    createPharmacy(createPharmacyInput: $createPharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeletePharmacy($deletePharmacyInput: DeletePharmacyInput!) {\n    deletePharmacy(deletePharmacyInput: $deletePharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation DeletePharmacy($deletePharmacyInput: DeletePharmacyInput!) {\n    deletePharmacy(deletePharmacyInput: $deletePharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Pharmacy($pharmacyId: String!) {\n    pharmacy(id: $pharmacyId) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      organization {\n        active\n        address\n        city\n        contact\n        country\n        createdAt\n        description\n        id\n        name\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query Pharmacy($pharmacyId: String!) {\n    pharmacy(id: $pharmacyId) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      organization {\n        active\n        address\n        city\n        contact\n        country\n        createdAt\n        description\n        id\n        name\n        updatedAt\n      }\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Pharmacies(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    pharmacies(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      pharmacies {\n        contactInfo\n        createdAt\n        id\n        location\n        name\n        organization {\n          id\n          name\n        }\n        updatedAt\n      }\n      total\n    }\n  }\n"): (typeof documents)["\n  query Pharmacies(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    pharmacies(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      pharmacies {\n        contactInfo\n        createdAt\n        id\n        location\n        name\n        organization {\n          id\n          name\n        }\n        updatedAt\n      }\n      total\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdatePharmacy($updatePharmacyInput: UpdatePharmacyInput!) {\n    updatePharmacy(updatePharmacyInput: $updatePharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdatePharmacy($updatePharmacyInput: UpdatePharmacyInput!) {\n    updatePharmacy(updatePharmacyInput: $updatePharmacyInput) {\n      contactInfo\n      createdAt\n      id\n      location\n      name\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreatePharmacyStock(\n    $createPharmacyStockInput: CreatePharmacyStockInput!\n  ) {\n    createPharmacyStock(createPharmacyStockInput: $createPharmacyStockInput) {\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      pharmacy {\n        id\n        name\n      }\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePharmacyStock(\n    $createPharmacyStockInput: CreatePharmacyStockInput!\n  ) {\n    createPharmacyStock(createPharmacyStockInput: $createPharmacyStockInput) {\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      pharmacy {\n        id\n        name\n      }\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PharmacyStock($pharmacyStockId: String!) {\n    PharmacyStock(id: $pharmacyStockId) {\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      pharmacy {\n        id\n        name\n      }\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query PharmacyStock($pharmacyStockId: String!) {\n    PharmacyStock(id: $pharmacyStockId) {\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      pharmacy {\n        id\n        name\n      }\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PharmacyStocksByPharmacy(\n    $pharmacyId: String!\n    $paginationArgs: PaginationArgs\n  ) {\n    pharmacyStocksByPharmacy(\n      pharmacyId: $pharmacyId\n      paginationArgs: $paginationArgs\n    ) {\n      pharmacyStocks {\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        pharmacy {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n"): (typeof documents)["\n  query PharmacyStocksByPharmacy(\n    $pharmacyId: String!\n    $paginationArgs: PaginationArgs\n  ) {\n    pharmacyStocksByPharmacy(\n      pharmacyId: $pharmacyId\n      paginationArgs: $paginationArgs\n    ) {\n      pharmacyStocks {\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        pharmacy {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PharmacyStocks(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    PharmacyStocks(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      pharmacyStocks {\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        pharmacy {\n          id\n          name\n        }\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n"): (typeof documents)["\n  query PharmacyStocks(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    PharmacyStocks(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      pharmacyStocks {\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        pharmacy {\n          id\n          name\n        }\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n      total\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Account {\n    account {\n      role\n      user {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n"): (typeof documents)["\n  query Account {\n    account {\n      role\n      user {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateProfile($updateProfileInput: UpdateProfileInput!) {\n    updateprofile(updateProfileInput: $updateProfileInput)\n  }\n"): (typeof documents)["\n  mutation UpdateProfile($updateProfileInput: UpdateProfileInput!) {\n    updateprofile(updateProfileInput: $updateProfileInput)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ResetPassword($resetPasswordInput: ResetPasswordInput!) {\n    resetPassword(resetPasswordInput: $resetPasswordInput)\n  }\n"): (typeof documents)["\n  mutation ResetPassword($resetPasswordInput: ResetPasswordInput!) {\n    resetPassword(resetPasswordInput: $resetPasswordInput)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Mutation($tokenConfirmationInput: TokenConfirmationInput!) {\n    tokenConfirmation(tokenConfirmationInput: $tokenConfirmationInput) {\n      access_token\n      user {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Mutation($tokenConfirmationInput: TokenConfirmationInput!) {\n    tokenConfirmation(tokenConfirmationInput: $tokenConfirmationInput) {\n      access_token\n      user {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        updatedAt\n        username\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Create($createUserInput: CreateUserInput!) {\n    create(createUserInput: $createUserInput) {\n      createdAt\n      email\n      emailConfirmationToken\n      id\n      isEmailConfirmed\n      name\n      organization {\n        id\n        name\n      }\n      updatedAt\n      username\n      role {\n        id\n        name\n        userType\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Create($createUserInput: CreateUserInput!) {\n    create(createUserInput: $createUserInput) {\n      createdAt\n      email\n      emailConfirmationToken\n      id\n      isEmailConfirmed\n      name\n      organization {\n        id\n        name\n      }\n      updatedAt\n      username\n      role {\n        id\n        name\n        userType\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query UserById($userByIdId: String!) {\n    userById(id: $userByIdId) {\n      createdAt\n      email\n      emailConfirmationToken\n      id\n      isEmailConfirmed\n      name\n      organization {\n        id\n        name\n      }\n      updatedAt\n      username\n      role {\n        id\n        name\n        userType\n      }\n    }\n  }\n"): (typeof documents)["\n  query UserById($userByIdId: String!) {\n    userById(id: $userByIdId) {\n      createdAt\n      email\n      emailConfirmationToken\n      id\n      isEmailConfirmed\n      name\n      organization {\n        id\n        name\n      }\n      updatedAt\n      username\n      role {\n        id\n        name\n        userType\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Users(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    users(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      users {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        organization {\n          id\n          name\n        }\n        updatedAt\n        username\n        role {\n          id\n          name\n          userType\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query Users(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    users(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      users {\n        createdAt\n        email\n        emailConfirmationToken\n        id\n        isEmailConfirmed\n        name\n        organization {\n          id\n          name\n        }\n        updatedAt\n        username\n        role {\n          id\n          name\n          userType\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateWarehouse($createWarehouseInput: CreateWarehouseInput!) {\n    createWarehouse(createWarehouseInput: $createWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateWarehouse($createWarehouseInput: CreateWarehouseInput!) {\n    createWarehouse(createWarehouseInput: $createWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteWarehouse($deleteWarehouseInput: DeleteWarehouseInput!) {\n    deleteWarehouse(deleteWarehouseInput: $deleteWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteWarehouse($deleteWarehouseInput: DeleteWarehouseInput!) {\n    deleteWarehouse(deleteWarehouseInput: $deleteWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query WarehouseDetails($warehouseId: String!) {\n    warehouse(id: $warehouseId) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        name\n        id\n      }\n    }\n  }\n"): (typeof documents)["\n  query WarehouseDetails($warehouseId: String!) {\n    warehouse(id: $warehouseId) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        name\n        id\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation GenerateSKU($generateSkuNameInput: CreateSkuNameInput!) {\n    generateSKU(generateSkuNameInput: $generateSkuNameInput) {\n      sku\n    }\n  }\n"): (typeof documents)["\n  mutation GenerateSKU($generateSkuNameInput: CreateSkuNameInput!) {\n    generateSKU(generateSkuNameInput: $generateSkuNameInput) {\n      sku\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query WarehouseList(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    warehouses(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      warehouses {\n        area\n        createdAt\n        id\n        location\n        updatedAt\n        name\n        organization {\n          name\n          id\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query WarehouseList(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    warehouses(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      warehouses {\n        area\n        createdAt\n        id\n        location\n        updatedAt\n        name\n        organization {\n          name\n          id\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation WarehouseStockCreate(\n    $createWarehouseStockInput: CreateWarehouseStockInput!\n  ) {\n    createWarehouseStock(\n      createWarehouseStockInput: $createWarehouseStockInput\n    ) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation WarehouseStockCreate(\n    $createWarehouseStockInput: CreateWarehouseStockInput!\n  ) {\n    createWarehouseStock(\n      createWarehouseStockInput: $createWarehouseStockInput\n    ) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteWarehouseStock(\n    $deleteWarehouseStockInput: DeleteWarehouseStockInput!\n  ) {\n    deleteWarehouseStock(\n      deleteWarehouseStockInput: $deleteWarehouseStockInput\n    ) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteWarehouseStock(\n    $deleteWarehouseStockInput: DeleteWarehouseStockInput!\n  ) {\n    deleteWarehouseStock(\n      deleteWarehouseStockInput: $deleteWarehouseStockInput\n    ) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query WarehouseStockDetails($warehouseStockId: String!) {\n    warehouseStock(id: $warehouseStockId) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n        organization {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query WarehouseStockDetails($warehouseStockId: String!) {\n    warehouseStock(id: $warehouseStockId) {\n      SKU {\n        id\n        sku\n      }\n      createdAt\n      finalQty\n      id\n      item {\n        id\n        name\n      }\n      totalMrpBaseUnit\n      totalWholesalePrice\n      updatedAt\n      warehouse {\n        id\n        name\n        organization {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query WarehouseStocks(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    warehouseStocks(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      warehouseStocks {\n        SKU {\n          id\n          sku\n        }\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query WarehouseStocks(\n    $pagination: Boolean\n    $paginationArgs: PaginationArgs\n    $searchText: String\n  ) {\n    warehouseStocks(\n      pagination: $pagination\n      paginationArgs: $paginationArgs\n      searchText: $searchText\n    ) {\n      total\n      warehouseStocks {\n        SKU {\n          id\n          sku\n        }\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query WarehouseStocksByWarehouse(\n    $warehouseId: String!\n    $paginationArgs: PaginationArgs\n  ) {\n    warehouseStocksByWarehouse(\n      warehouseId: $warehouseId\n      paginationArgs: $paginationArgs\n    ) {\n      total\n      warehouseStocks {\n        SKU {\n          id\n          sku\n        }\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query WarehouseStocksByWarehouse(\n    $warehouseId: String!\n    $paginationArgs: PaginationArgs\n  ) {\n    warehouseStocksByWarehouse(\n      warehouseId: $warehouseId\n      paginationArgs: $paginationArgs\n    ) {\n      total\n      warehouseStocks {\n        SKU {\n          id\n          sku\n        }\n        createdAt\n        finalQty\n        id\n        item {\n          id\n          name\n        }\n        totalMrpBaseUnit\n        totalWholesalePrice\n        updatedAt\n        warehouse {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateWarehouseMutation(\n    $updateWarehouseInput: UpdateWarehouseInput!\n  ) {\n    updateWarehouse(updateWarehouseInput: $updateWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateWarehouseMutation(\n    $updateWarehouseInput: UpdateWarehouseInput!\n  ) {\n    updateWarehouse(updateWarehouseInput: $updateWarehouseInput) {\n      area\n      createdAt\n      id\n      location\n      updatedAt\n      name\n      organization {\n        id\n        name\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;