export enum USER_ROLE {
  ADMIN = "ADMIN",
  STAFF = "STAFF",
}

export enum USER_PERMISSION_FIELDS {
  ITEM_CATEGORIES_MANAGEMENT = "ITEM_CATEGORIES_MANAGEMENT",
  ITEM_MANAGEMENT = "ITEM_MANAGEMENT",
  ORGANIZATION_MANAGEMENT = "ORGANIZATION_MANAGEMENT",
  PHARMACY_MANAGEMENT = "PHARMACY_MANAGEMENT",
  PROFILE = "PROFILE",
  STAFF_MANAGEMENT = "STAFF_MANAGEMENT",
  STOCK_MANAGEMENT = "STOCK_MANAGEMENT",
  USER_MANAGEMENT = "USER_MANAGEMENT",
  USER_PERMISSION = "USER_PERMISSION",
  WAREHOUSE_MANAGEMENT = "WAREHOUSE_MANAGEMENT",
  STOCK_MANAGEMENT_ADMIN = "STOCK_MANAGEMENT_ADMIN",
  STOCK_MANAGEMENT_STAFF = "STOCK_MANAGEMENT_STAFF",
}

export enum USER_PERMISSION_CAPABILITIES {
  VIEW = "VIEW",
  EDIT = "EDIT",
  CREATE = "CREATE",
  DELETE = "DELETE",
}
